services:
  auth-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: arseniherasimovichinnowise/auth-service
    depends_on:
      - auth-service-db
    networks:
      - backend-net
      - auth-service-net
    environment:
      - DB_HOST=auth-service-db
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - EUREKA_URL=http://discovery-service:8761/eureka/
      - JWT_SECRET=${JWT_SECRET}

  auth-service-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - auth-service-net
    volumes:
      - auth-service-postgres-data:/var/lib/postgresql/data

volumes:
  auth-service-postgres-data: {}

networks:
  backend-net:
    external: true
  auth-service-net:
    driver: bridge