spring:
  application:
    name: auth-service
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
    enabled: true
  jpa:
    open-in-view: false
  security:
    jwt:
      secret: ${JWT_SECRET}
      access-token-ttl: ${ACCESS_TOKEN_TTL:900}
      refresh-token-ttl: ${REFRESH_TOKEN_TTL:604800}
      refresh-token-cleaner-cron: 0 0 0 * * *