spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
    enabled: true
  jpa:
    open-in-view: false
  security:
    jwt:
      secret: ${JWT_SECRET}
      access-token-ttl: ${ACCESS_TOKEN_TTL:900}
      refresh-token-ttl: ${REFRESH_TOKEN_TTL:604800}
      refresh-token-cleaner-cron: 0 0 0 * * *
  autoconfigure:
    exclude:
      - net.devh.boot.grpc.server.autoconfigure.GrpcServerSecurityAutoConfiguration
eureka:
  instance:
    metadata-map:
      grpc.port: 9090
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
logging:
  level:
    com.innowise: ${APP_LOGGING_LEVEL:info}

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true